### ISSUE TITLE
Add automated unit tests

### ISSUE THREAD

**Issue by Sherlouk** [ollieatkinson/Guise#8]
Would need to change a few things, for example being able to extract environment variables from a protocol rather than mocking the entire `ProcessInfo`.

I believe there are several chunks that can be individually tested very nicely, but also the start-to-end flow can be quite neatly tested by allowing the save to disk function to be configured via a block.

This could coincide with work to enable CI, and tools like Circle allow you to choose Xcode versions. I believe due to SourceKit changes, the output will likely change overtime as the Xcode versions update - so this is still something valid to test to ensure functionality still works.

**Comment by ollieatkinson** [comment]
And off the back of doing this ticket, getting it setup in travis (or tool a-like) should be a priority

**Comment by Sherlouk** [comment]
@ollieatkinson Good to close this issue? Tests will be an ongoing thing, but the initial stuff is setup and CI is seemingly working?
