### ISSUE TITLE
What should we call this tool? 

### ISSUE THREAD

**Issue by ollieatkinson** [ollieatkinson/Guise#9]
`swift-public-api-generator` whilst being verbose, is clearly un-imaginative. Any suggestions for names?

e.g.
`swiftapi`
`facade`

**Comment by Sherlouk** [comment]
`facade`
`guise` (Doesn't matter what's behind the mask)
`interface`

**Comment by ollieatkinson** [comment]
I like Guise, let's go for that! Thanks @Sherlouk
